### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by chrisjj** [mhuebert/maria#263] opened 2023-02-09 22:23 UTC
...

**Comment by paul-marechal** [comment] 2023-02-15 20:04
Regarding the issue you originally reported, it seems like you were missing the following definition:

```clojure
(def rainbow
  ["red" "orange" "yellow" "green" "blue" "indigo" "violet"])
```

**Comment by chrisjj** [comment] 2023-02-15 20:07
Yes! I deleted the issue because I discovered just that.

Well Done for such a great resource!

**Comment by paul-marechal** [comment] 2023-02-15 20:08
The issue is still up and opened though, you may want to look into closing it now.

**Comment by chrisjj** [comment] 2023-02-15 20:15
Thanks. Done.

**Closed** 2023-02-15 20:14 UTC
