### ISSUE TITLE
M1 causes auto scroll

### ISSUE THREAD

**Issue by jackrusher** [mhuebert/maria#123] opened 2017-10-01 16:04 UTC
### Issue:

If I eval a form, then scroll down to the bottom a long doc (the intro, say), then press M1, the window jumps back up the code block containing the last form I eval'd.

### Environment:

  - Browser:
Chrome, Safari
  - Platform (Mac/Windows/Linux):
Mac

**Comment by mhuebert** [comment] 2017-10-01 16:12
Side-effect of some deliberate but inadequate code designed to improve keyboard navigation. Bug :).

**Comment by mhuebert** [comment] 2017-10-01 16:32
Actually this wasn't caused by the keyboard-nav stuff. CodeMirror by default scrolls itself into view when you set the cursor or selection (understandably). Easy to disable.

**Comment by mhuebert** [comment] 2017-10-01 16:46
Pushed fix to `dev`

**Closed by mhuebert** 2017-10-01 16:46 UTC
Labels: bug
